apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tim-mcp
spec:
  parentRefs:
    - name: mcp-gateway
      namespace: mcp-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /tim
      backendRefs:
        - name: tim-mcp
          port: 8080
